"""Create JobPost Model via Flask-SQLAlchemy, create migrations via Flask-Migrate, and create the initial version of database.

Revision ID: fc1a2c0afd72
Revises: 
Create Date: 2024-06-14 16:12:25.270032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1a2c0afd72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_post',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('duties', sa.String(), nullable=False),
    sa.Column('qualifications', sa.String(), nullable=False),
    sa.Column('benefits', sa.String(), nullable=False),
    sa.Column('c_name', sa.String(), nullable=False),
    sa.Column('c_img', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_post')
    # ### end Alembic commands ###
